import { BillArtCollection, BillVersion, ChainId, PreTGEConfig } from '../types'
import tokens from './tokens'

const preTGEBonds: PreTGEConfig[] = [
  {
    version: '2.1.2',
    index: 1,
    chainId: ChainId.MAINNET,
    vestingTimeString: '10 Months',
    tgeString: 'June 2nd',
    shortDescription:
      'AIRAS (Artificial Intelligence Real Assets System) is a comprehensive platform dedicated to leveraging AI and Blockchain for real world asset management, investment, and optimization. It powers autonomous applications across industries, enabling efficient, transparent, and scalable asset management. The AIRAS token fuels the ecosystem through transactions, governance, and incentives.',
    tags: ['AI'],
    contractAddress: { [ChainId.MAINNET]: '0x6402BD234187a695352085518C835131494E5E35' },
    billVersion: BillVersion.TieredSale,
    billType: 'fcfs',
    lpToken: tokens.usdc,
    earnToken: tokens.airas,
    billNnftAddress: {
      [ChainId.MAINNET]: '0x499b654b0A7f9979CC315190C09cA2633809B8dF',
    },
    soldOut: false,
    billArt: { collection: BillArtCollection.ApeBond_Collection1 },
    redeemTime: 1748624400,
    tgePrice: 0.0005,
    twitter: 'https://x.com/AirasNetwork',
    projectLink: 'https://www.airas.com/',
  },
  {
    version: '2.1.2',
    index: 2,
    chainId: ChainId.MAINNET,
    vestingTimeString: '5 Months',
    tgeString: 'June 2nd',
    shortDescription:
      'AIRAS (Artificial Intelligence Real Assets System) is a comprehensive platform dedicated to leveraging AI and Blockchain for real world asset management, investment, and optimization. It powers autonomous applications across industries, enabling efficient, transparent, and scalable asset management. The AIRAS token fuels the ecosystem through transactions, governance, and incentives.',
    tags: ['AI'],
    contractAddress: { [ChainId.MAINNET]: '0xBFD8eA911959deefC5F369438c14eb304Fe6FD13' },
    billVersion: BillVersion.TieredSale,
    billType: 'fcfs',
    lpToken: tokens.usdc,
    earnToken: tokens.airas,
    billNnftAddress: {
      [ChainId.MAINNET]: '0x499b654b0A7f9979CC315190C09cA2633809B8dF',
    },
    soldOut: false,
    billArt: { collection: BillArtCollection.ApeBond_Collection1 },
    redeemTime: 1753963200, // July 31th 12:00UTC
    tgePrice: 0.0005,
    twitter: 'https://x.com/AirasNetwork',
    projectLink: 'https://www.airas.com/',
  },
  {
    version: '2.1.2',
    index: 3,
    chainId: ChainId.MAINNET,
    vestingTimeString: '10 Months',
    tgeString: 'July 30th',
    shortDescription: `Murloc Coin is a Solana-based memecoin born from the chaotic spirit of the Murlocs — iconic creatures from the depths of fantasy gaming lore. Led by the unpredictable Gluk’Krogg, the Murlocs have escaped their old world and launched a full-scale invasion of the blockchain. <span style="font-weight: 700">This ERC-20 version of the token will be exchangeable 1:1 for the native equivalent on Solana closer to TGE.</span>`,
    tags: ['Meme'],
    contractAddress: { [ChainId.MAINNET]: '0x5dC6316Bfd0615b6C6573B3E06767A2feD5cCB89' },
    billVersion: BillVersion.TieredSale,
    billType: 'fcfs',
    lpToken: tokens.usdc,
    earnToken: tokens.mrlc,
    billNnftAddress: {
      [ChainId.MAINNET]: '0x499b654b0A7f9979CC315190C09cA2633809B8dF',
    },
    soldOut: false,
    billArt: { collection: BillArtCollection.ETH_Collection1 },
    redeemTime: 1753894800,
    tgePrice: 0.01,
    twitter: 'https://x.com/MurlocOfficial',
    projectLink: 'https://murloc.gg/',
  },
  {
    version: '2.1.2',
    index: 4,
    chainId: ChainId.UNICHAIN,
    vestingTimeString: 'Max-Locked veCATX',
    tgeString: 'July 16th',
    shortDescription: `Catex is the MetaDEX layer for Uniswap V4, combining automated liquidity, ve(3,3) governance, and strategic incentives to support LPs and hook builders. The ecosystem is powered by four synergistic tokens, with CATX at its core, driving governance and liquidity. Supporting this system is bveCATX, a non-liquid voter incentive token redeemable 1:1 for veCATX, which promotes active participation by rewarding engaged voters and redistributing incentives via oCATX buybacks to fuel long-term alignment.`,
    tags: ['DeFi'],
    contractAddress: { [ChainId.UNICHAIN]: '0x64384402c89297db8c8F77A95CE1bC4177F8fCAc' },
    billVersion: BillVersion.TieredSale,
    billType: 'fcfs',
    lpToken: tokens.usdc,
    earnToken: tokens.bvecatx,
    billNnftAddress: {
      [ChainId.UNICHAIN]: '0x1b7858f745211dBa1387fE30124eBCa2D706D7Dd',
    },
    soldOut: false,
    billArt: { collection: BillArtCollection.ApeBond_Collection1 },
    redeemTime: 1752670800,
    tgePrice: 0.1,
    twitter: 'https://x.com/Catex_Fi',
    projectLink: 'https://app.catex.fi/',
    warningCard: 'This is a Pre-TGE Bond for bveCATX, redeemable 1:1 for veCATX at max lock upon listing.',
  },
  {
    version: '2.1.2',
    index: 5,
    chainId: ChainId.BSC,
    vestingTimeString: '8 Months',
    tgeString: 'Sep 22nd',
    shortDescription: `ChimpX is an all-in-one DeFi platform that makes crypto trading, bridging, and investing simple and fast. With zero native gas fees, one-click execution, and a seamless cross-chain experience powered by Universal Accounts, users can trade any token on any blockchain effortlessly. The CHIMP token unlocks exclusive features and benefits within the ChimpX ecosystem.`,
    tags: ['DeFi'],
    contractAddress: { [ChainId.BSC]: '0x9dA65b945fC9A197e4c35Ce8c315c3122B58C164' },
    billVersion: BillVersion.TieredSale,
    billType: 'fcfs',
    lpToken: tokens.usdt,
    earnToken: tokens.chimp,
    billNnftAddress: {
      [ChainId.BSC]: '0xB75BE16984A27d3023e1cF744E2587e9Aa8750c9',
    },
    soldOut: true,
    billArt: { collection: BillArtCollection.ApeBond_Collection1 },
    redeemTime: 1758546000,
    tgePrice: 0.6,
    twitter: 'https://x.com/ChimpxAI',
    projectLink: 'https://chimpx.ai/',
  },
  // {
  //   version: '2.1.2',
  //   index: 6,
  //   chainId: ChainId.MATIC,
  //   vestingTimeString: '6 Months',
  //   tgeString: 'Sep 3rd',
  //   shortDescription: `PolyPicks is redefining sports betting by merging AI-powered intelligence, proprietary data analysis, and a staking-based revenue-sharing model into a seamless decentralized experience. Its self-improving AI retrains every 4 hours, ensuring real-time optimization. By staking in the Poly Pool, users earn immediate revenue share while preserving an edge against dilution, an ecosystem built around the $PICKS token.`,
  //   tags: ['Gambling'],
  //   contractAddress: { [ChainId.MATIC]: '0x65AD770a484B9bc2b039c57A82116530F79441a8' },
  //   billVersion: BillVersion.TieredSale,
  //   billType: 'fcfs',
  //   lpToken: tokens.usdt,
  //   earnToken: tokens.picks,
  //   billNnftAddress: {
  //     [ChainId.MATIC]: '0x8860ABc05FefEF93306c8d65a5eFD421F155d67E',
  //   },
  //   soldOut: false,
  //   billArt: { collection: BillArtCollection.ApeBond_Collection1 },
  //   redeemTime: 1757520000,
  //   tgePrice: 0.00095,
  //   twitter: 'https://x.com/polypicksai',
  //   projectLink: 'https://polypicks.ai/',
  // },
  // {
  //   version: '2.1.2',
  //   index: 7,
  //   chainId: ChainId.MATIC,
  //   vestingTimeString: '6 Months',
  //   tgeString: 'Sep 3rd',
  //   shortDescription: `PolyPicks is redefining sports betting by merging AI-powered intelligence, proprietary data analysis, and a staking-based revenue-sharing model into a seamless decentralized experience. Its self-improving AI retrains every 4 hours, ensuring real-time optimization. By staking in the Poly Pool, users earn immediate revenue share while preserving an edge against dilution, an ecosystem built around the $PICKS token.`,
  //   tags: ['Gambling'],
  //   contractAddress: { [ChainId.MATIC]: '0x65AD770a484B9bc2b039c57A82116530F79441a8' },
  //   billVersion: BillVersion.TieredSale,
  //   billType: 'fcfs',
  //   lpToken: tokens.picksMockUsdt,
  //   earnToken: tokens.picksReal,
  //   billNnftAddress: {
  //     [ChainId.MATIC]: '',
  //   },
  //   soldOut: false,
  //   billArt: { collection: BillArtCollection.ApeBond_Collection1 },
  //   redeemTime: 1757520000,
  //   tgePrice: 0.00095,
  //   twitter: 'https://x.com/polypicksai',
  //   projectLink: 'https://polypicks.ai/',
  // },
]

export default preTGEBonds
