name: Build

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run start
        run: yarn start
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
